### PR TITLE
expose API as an interface

### LINKED ISSUE #42: API as an interface
Hello, it would be create if the lib exposes its API as an interface.

With that adjustment classes that depends on your API are testable b/c popular multiplatform mocking libraries are only support to mock interfaces [[MockKMP](https://github.com/kosi-libs/MocKMP)] [[Mockative](https://github.com/mockative/mockative)].

Best

### PR DESCRIPTION
**Pull request by cleemansen**
close #42

### CODE REVIEW

**Comment by cleemansen** [comment]
I started this PR before checking any pending PRs - sorry about that! There is already a [PR addressing the same issue](https://github.com/Liftric/KVault/pull/47/)!

**Comment by cleemansen** [comment]
This approach does not make use of the KMM `expect/actual` feature. It is just a simple `interface/implementation` approach.

Also this PR is a breaking API change - there is no downgrade compatibility. The adjusted `README.md` highlights the change.

As the tests are green I have a good feeling. But I did not tested the library in a real Android app. I wish there was an Android example app (similar to the `iostests` app). But I had no luck to add this android-example-app. I don't know how to reference the library source code (`./src`) at this example app (gradle?).

So please review this approach carefully and let me know if this isn't the correct approach for multi-platform libraries. I took [some recommendations from the kmm-documentation](https://kotlinlang.org/docs/multiplatform-library.html) (w/o the factory class as the two `kvault` implementations need different parameters).

**Comment by cleemansen** [comment]
I was able to test the changed API in my real world app by installing this PR to my [local maven repo](https://kotlinlang.org/docs/multiplatform-library.html#publish-your-library-to-the-local-maven-repository) via `./gradlew publishToMavenLocal` and reference this version via `mavenLocal()`.

As expected I had to change my dependency graph (we are using [koin](https://insert-koin.io/) - but this doesn't really matter):

`./shared/src/androidMain/package/di/PlatformModule.kt`

```
single<KVault> { KVaultEncryptedSharedPreferences(context = get(), fileName = "any") }
```

`./shared/src/iosMain/package/di/PlatformModule.kt`

```
single<KVault> { KVaultKeychain("any") }
```

My Android and my iOS apps are running as expected. And unit tests can run w/ a mock of the interface `KVault`.

**Comment by benjohnde** [comment]
@cleemansen thanks for your efforts, I favour the variant with actual / expect, so I will look at #47 more deeply tomorrow. Thanks for your contribution!

**Pull request closed without merging**
