### PR TITLE
kotPref like property delegates abstraction

### PR DESCRIPTION
**Pull request by NightGoat**
I really like your library, so i thought it would be nice to have property delegates as in kotPref library, it makes much less code writing for accessing properties. Example from my project:
```
class SettingsProvider : KVaultPref() {
    override val kvault = KvaultProvider().provide()
    private var pinCode: String by stringPref(PIN_CODE_KEY)
    var isPinCodeSet: Boolean by booleanPref(IS_PIN_CODE_SET_KEY)
}
```

### CODE REVIEW

**Comment by gaebel** [comment]
Sorry for the late reply, @NightGoat! I like the property delegate approach, I'll review your PR tomorrow :)

**Comment by gaebel** [comment]
Generally I'm fine with your implementation, though I was thinking of how we could improve it:

- I'd implement the property delegates by creating extension functions on the KVault class.
- It would be nice if we would be able to resolve to null
- We could make the key optional and use the property name if it is absence

```kotlin
val pinCode: String? by kvault.stringOrNull()
val legacyPinCode: String? by kvault.stringOrNull(key = "pin_code")
val hasPin: Boolean by kvault.bool(defaultValue = false)
val appInstallDate: Long by kvault.long() // Would throw if null and no default value provided
```

Would be even nicer to use generics, but then I think we can only check the type on runtime (due to only one upper class bound in where clause, or function overloads).

**Comment by gaebel** [comment]
We could also add a property delegate for `existsObject()`:

```kotlin
val hasPin: Boolean by kvault.exists()
```

**Comment by NightGoat** [comment]
Okay, I updated my PR: I added extensions, keys nullability and exists() extension. Unfortunately I could not find a solution for a change nullability on the fly, but i added nullable extensions as well

**Comment by NightGoat** [comment]
will someone merge it? i cant

**Comment by gaebel** [comment]
Mostly looking good to me. I'm hesitant to use the suffix "pref", since we're not only using SharedPreferences (also doesn't feel in line with the rest of the library). The separate abstract class delegate is redundant imo, I guess it's meant to be able to drop "kvault" in the delegate call, though I'd prefer the verboseness.

**Comment by NightGoat** [comment]
ReadWriteProperty needs to know what class is makes the changes in the delegate property, so if you use only the extension you need to write not the only kvault in the beginning but add the class that uses that. For example:
```
class Foo() {
   val kvault = Kvault()
   val pin = kvault.stringPref<Foo>("", "")
}
```
The abstraction takes it boilerplate from you.
```
class Foo(): KvaultPref {
   override val kvault = Kvault()
   val pin = stringPref("", "")
}
```
As about the name - i just used name that would be familiar to a lot of people, since kotPref is well known library. You can use whatever you want

**Comment by gaebel** [comment]
You could also just use Any? as the delegate owner type.

**Comment by NightGoat** [comment]
Okay, i will delete abstraction and use Any as owner type, i can change prefix to vault: `stringVault`. But thats it, take it or leave it :)

**Comment by NightGoat** [comment]
Is any alive here?

**Pull request closed without merging**
