### PR TITLE
Refactor API to use an interface.

### LINKED ISSUE #42: API as an interface
Hello, it would be create if the lib exposes its API as an interface.

With that adjustment classes that depends on your API are testable b/c popular multiplatform mocking libraries are only support to mock interfaces [[MockKMP](https://github.com/kosi-libs/MocKMP)] [[Mockative](https://github.com/mockative/mockative)].

Best

### PR DESCRIPTION
**Pull request by jadar**
Interfaces allow mocking libraries to mock our types more easily. This will prevent users of KVault from having to wrap KVault with another type when they want to test code which uses it.

This will be a breaking API change, unfortunately, because any users which extend the `KVault` class will have to extend `KVaultImpl` instead.

This follows the Kotlin coding convention pattern, [here](https://kotlinlang.org/docs/coding-conventions.html#function-names)

Closes #42

### CODE REVIEW

**Comment by benjohnde** [comment]
@jadar sry due to other PRs this one is no conflicting. Do you mind resolving the conflicts? Overall your implementation looks promising, breaking changes cannot be avoided which is fine IMHO.

**Comment by jadar** [comment]
@benjohnde I merged the upstream `master` branch. Should be up-to-date now.

**Comment by benjohnde** [comment]
@canonall @ductavius @tknoelle we don't need to use a new published version with breaking api changes soon, but before merge I wanted to get a short confirm from you guys as well!

**Comment by benjohnde** [comment]
Thanks a million @jadar !

**Comment by tknoelle** [comment]
The changes are fine for me @benjohnde.

Thanks a lot @jadar

**Pull request merged**
